---
- name: Build environment
  hosts: db
  become: yes

  tasks:
    - name: Ensure java is present
      apt:
        name: default-jdk
        state: present
    - name: Ensure git is present
      apt:
        name: git
        state: present
    - name: Ensure maven is present
      apt:
        name: maven
        state: present
    - name: Cloning the bosfosse repository
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /tmp/boxfuse-sample-java-war-hello
    - name: Build
      shell: "mvn -f /tmp/boxfuse-sample-java-war-hello/pom.xml package"
    - name: Fetch build
      fetch:
        src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
        dest: /tmp/hello-1.0.war
        flat: yes

- name: Prod environment
  hosts: web
  become: yes

  tasks:
  - name: Ensure tomcat package is present
    apt:
      name: tomcat9
      state: present

  - name: Ensure tomcat service is started
    service:
      name: tomcat9
      state: started

  - name: Copy build
    copy:
      src: /tmp/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/
